#!/usr/bin/env python3
"""bin2c.py in.bin out.h symbol  -- emit a C array (used to embed t2000.abs)"""
import sys
d = open(sys.argv[1], 'rb').read()
with open(sys.argv[2], 'w') as f:
    f.write("/* generated by mac/bin2c.py - do not edit */\n")
    f.write("static const unsigned char %s[%d] = {\n" % (sys.argv[3], len(d)))
    for i in range(0, len(d), 24):
        f.write(",".join(str(b) for b in d[i:i+24]) + ",\n")
    f.write("};\n")
